Repository Saebasol/Heliotrope, pull requests merged in 2021-03, with the labels that each got.

#162 test(test): status -> status_code
  test/test_response.py
  test/test_unexpected_response.py
Labels: hotfix, test

#159 feat(ranking_management): add month data
  Heliotrope/utils/database/ranking_management.py
Labels: feature

#163 Release 3.5.0
  Heliotrope/__init__.py
  Heliotrope/utils/database/ranking_management.py
  requirements.txt
  test/test_response.py
  test/test_unexpected_response.py
Labels: Release, feature

#169 Release 3.5.1 (Hotfix)
  Heliotrope/__init__.py
  Heliotrope/utils/hitomi/galleryinfomodel.py
Labels: Release, hotfix

#178 Release 4.0.0-beta
  azure-pipelines.yml
  heliotrope/__init__.py
  heliotrope/api/__init__.py
  heliotrope/api/hitomi/__init__.py
  heliotrope/api/hitomi/images.py
  heliotrope/database/models/hitomi.py
  heliotrope/database/query.py
  heliotrope/routes/__init__.py
  heliotrope/routes/about.py
  heliotrope/routes/api/__init__.py
  heliotrope/routes/api/count.py
  heliotrope/routes/api/hitomi/__init__.py
  heliotrope/routes/api/hitomi/galleryinfo.py
  heliotrope/routes/api/hitomi/images.py
  heliotrope/routes/api/hitomi/info.py
  heliotrope/routes/api/hitomi/list.py
  heliotrope/routes/api/proxy.py
  heliotrope/server.py
  heliotrope/utils/decorators.py
  heliotrope/utils/requester.py
  heliotrope/utils/response.py
  heliotrope/utils/tasks/mirroring.py
  heliotrope/utils/typed.py
  tests/conftest.py
  tests/test_about.py
  tests/test_count.py
  tests/test_galleryinfo.py
  tests/test_images.py
  tests/test_info.py
  tests/test_list.py
  tests/test_proxy.py
Labels: Release
