Repository Saebasol/Heliotrope, pull requests merged in 2022-09, with the labels that each got.

#278 feat: support query on random endpoint
  heliotrope/abc/database.py
  heliotrope/database/odm/__init__.py
  heliotrope/database/orm/__init__.py
  heliotrope/rest/api/hitomi/list.py
  heliotrope/rest/api/hitomi/random.py
  heliotrope/rest/api/hitomi/search.py
  tests/test_random.py
Labels: PR: feat

#277 fix(odm): use allowDiskUse
  heliotrope/database/odm/__init__.py
Labels: PR: fix, ODM

#288 release(heliotrope): bump up 6.4.2 to 6.4.4
  heliotrope/__init__.py
Labels: PR: release
